image: node:latest

before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn install
    
cache:
  paths:
    - node_modules/
    - .yarn

build:
  script:
    - yarn build